### ISSUE TITLE
方式一的使用及方式二中拆分后混淆名称问题

### ISSUE THREAD

**Issue by sixgodw** [iqiyi/dexSplitter#2]
你好，我通过对你们提供的demo来分包，有几个问题
1、方式一：hack tools.builder.gradle 方式，需要编译tools.builder.gradle源码，该怎么编译，编译后的文件怎么使用，能否说的更具体些
2、通过方式二，成功的将你们的demo按模块进行了区分，但是模块名都是混淆后的，比如：class1、class2之内的，请问是可能是哪个步骤出问题了

**Comment by jjbheda** [comment]
1. 编译tools.builder.gradle源码 需要去官网下载源码(需翻墙)，目前gradle即可编译，具体步骤及使用可自行搜索网上教程。 针对更改文件，工程中已经做了说明。
2. 目前的拆分目的，是为了测量真实的线上apk包中各模块代码占比，因此拆分的class必然是混淆过的。如果拆分为debug模式，就失去拆分的意义了。如果想知道混淆对应的实际代码，只需要针对mapping文件做个映射即可。

**Comment by yangli1120** [comment]
用的是第二种方式，按extra/hack_description.txt描述的那样，执行完apk_splitter.py脚本得到的apk，classes.dex确实分割了，但是分割后的dex都是classes2.dex，classes4.dex，classes5.dex，classes6.dex这样的，没有像readme里描述的那样，是直白的android_sys.dex，hostProject.dex，far.dex，boo.dex等等。而且也没有生成apk_spliter_result.txt文件。是哪里没配对吗？
![image](https://user-images.githubusercontent.com/4456881/61630024-26b78780-acb9-11e9-8768-0dbc9bd95200.png)
![image](https://user-images.githubusercontent.com/4456881/61630033-2fa85900-acb9-11e9-80e7-33831e04172a.png)

**Comment by jjbheda** [comment]
![image](https://user-images.githubusercontent.com/9442848/62128573-4842ef80-b307-11e9-97ef-05f999e8694e.png)
请仔细阅读下2.2.7 这一条。 因为android打包阶段，会对dex文件重新命名，所以dx阶段的命名最后也会失效的。 直接hack dx.jar 只能通过反编译来确定归属。早期我们也是借助反编译工具，配合简单脚本分析的。
